version: "3.9"

services:
  sammy-app:
    container_name: sammy-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./lib:/app/lib
      - ./models:/app/models
      - ./workers:/app/workers
      - ./public:/app/public
      # Don't mount node_modules (let container handle it)
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    restart: always
    networks:
      - sammy_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  sammy_network:
    name: sammy_dev_network
