import { GraphState } from "../../src/app/api/agent/route";

/**
 * Sends the post generated by the agent to Twitter/X.
 * Assumes the agent has already handled platform rules, formatting, and content.
 */
export async function twitterPosting(
  state: GraphState
): Promise<Partial<GraphState>> {
  const { post, platform, threadId } = state;

  if (!post) {
    throw new Error("Missing 'post' in state");
  }

  console.log("📡 Sending post to Twitter/X endpoint:", {
    post,
    platform,
    threadId,
  });

  const res = await fetch(
    `${process.env.NEXT_PUBLIC_BASE_URL}/api/postings/x-posting`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ post, platform }),
    }
  );

  if (!res.ok) {
    let bodyText: string;

    try {
      const errorData = await res.json();
      console.error("External API failed with JSON:", errorData);
      bodyText = JSON.stringify(errorData, null, 2);
    } catch {
      bodyText = await res.text();
      console.error("External API failed with raw response:", bodyText);
    }

    throw new Error(
      `External API error (status: ${res.status})\nResponse: ${bodyText}`
    );
  }

  const data = await res.json();

  return {
    ...state,
    post,
    threadId,
    result: data,
  };
}
